// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieAppPortfolio.DataServiceLayer;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MovieAppPortfolio.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MovieAppPortfolio.DataServiceLayer.TitlePrincipal.TitlePrincipals", b =>
                {
                    b.Property<string>("tconst")
                        .HasColumnType("text")
                        .HasColumnName("tconst");

                    b.Property<string>("nconst")
                        .HasColumnType("text")
                        .HasColumnName("nconst");

                    b.Property<int>("ordering")
                        .HasColumnType("integer")
                        .HasColumnName("ordering");

                    b.Property<string>("category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("characters")
                        .HasColumnType("text")
                        .HasColumnName("characters");

                    b.Property<string>("job")
                        .HasColumnType("text")
                        .HasColumnName("job");

                    b.HasKey("tconst", "nconst", "ordering");

                    b.ToTable("title_principals", "movie_app");
                });

            modelBuilder.Entity("MovieAppPortfolio.DataServiceLayer.entities.Bookmark", b =>
                {
                    b.Property<int>("BookmarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bookmark_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookmarkId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NConst")
                        .HasColumnType("text")
                        .HasColumnName("nconst");

                    b.Property<string>("TConst")
                        .HasColumnType("text")
                        .HasColumnName("tconst");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("BookmarkId");

                    b.HasIndex("NConst");

                    b.HasIndex("TConst");

                    b.HasIndex("UserId");

                    b.ToTable("bookmark", "movie_app");
                });

            modelBuilder.Entity("MovieAppPortfolio.DataServiceLayer.entities.Genre", b =>
                {
                    b.Property<int>("genreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("genreId"));

                    b.Property<string>("genreName")
                        .HasColumnType("text")
                        .HasColumnName("genre_name");

                    b.HasKey("genreId");

                    b.ToTable("genre", "movie_app");
                });

            modelBuilder.Entity("MovieAppPortfolio.DataServiceLayer.entities.GenreTitle", b =>
                {
                    b.Property<int>("genreTitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("genre_title_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("genreTitleId"));

                    b.Property<int>("genreId")
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    b.Property<string>("tconst")
                        .HasColumnType("text")
                        .HasColumnName("tconst");

                    b.HasKey("genreTitleId");

                    b.ToTable("genre_title", "movie_app");
                });

            modelBuilder.Entity("MovieAppPortfolio.DataServiceLayer.entities.NameBasic", b =>
                {
                    b.Property<string>("nconst")
                        .HasColumnType("text")
                        .HasColumnName("nconst");

                    b.Property<int?>("birthYear")
                        .HasColumnType("integer")
                        .HasColumnName("birth_year");

                    b.Property<int?>("deathYear")
                        .HasColumnType("integer")
                        .HasColumnName("death_year");

                    b.Property<string>("primaryName")
                        .HasColumnType("text")
                        .HasColumnName("primary_name");

                    b.HasKey("nconst");

                    b.ToTable("name_basics", "movie_app");
                });

            modelBuilder.Entity("MovieAppPortfolio.DataServiceLayer.entities.NameRating", b =>
                {
                    b.Property<string>("nconst")
                        .HasColumnType("text")
                        .HasColumnName("nconst");

                    b.Property<string>("NameBasicnconst")
                        .HasColumnType("text");

                    b.Property<DateTime>("lastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<decimal?>("weightedRating")
                        .HasColumnType("numeric")
                        .HasColumnName("weighted_rating");

                    b.HasKey("nconst");

                    b.HasIndex("NameBasicnconst");

                    b.ToTable("name_rating", "movie_app");
                });

            modelBuilder.Entity("MovieAppPortfolio.DataServiceLayer.entities.OmdbData", b =>
                {
                    b.Property<string>("tconst")
                        .HasColumnType("text")
                        .HasColumnName("tconst");

                    b.Property<string>("plot")
                        .HasColumnType("text")
                        .HasColumnName("plot");

                    b.Property<string>("poster")
                        .HasColumnType("text")
                        .HasColumnName("poster");

                    b.HasKey("tconst");

                    b.ToTable("omdb_data", "movie_app");
                });

            modelBuilder.Entity("MovieAppPortfolio.DataServiceLayer.entities.SearchHistory", b =>
                {
                    b.Property<int>("SearchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("search_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SearchId"));

                    b.Property<string>("SearchQuery")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_query");

                    b.Property<DateTime>("SearchTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("search_time");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("SearchId");

                    b.HasIndex("UserId");

                    b.ToTable("search_history", "movie_app");
                });

            modelBuilder.Entity("MovieAppPortfolio.DataServiceLayer.entities.TitleBasic", b =>
                {
                    b.Property<string>("tconst")
                        .HasColumnType("text")
                        .HasColumnName("tconst");

                    b.Property<int?>("endYear")
                        .HasColumnType("integer")
                        .HasColumnName("end_year");

                    b.Property<bool?>("isAdult")
                        .HasColumnType("boolean")
                        .HasColumnName("is_adult");

                    b.Property<string>("originalTitle")
                        .HasColumnType("text")
                        .HasColumnName("original_title");

                    b.Property<string>("primaryTitle")
                        .HasColumnType("text")
                        .HasColumnName("primary_title");

                    b.Property<int?>("runtimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("runtime_minutes");

                    b.Property<int?>("startYear")
                        .HasColumnType("integer")
                        .HasColumnName("start_year");

                    b.Property<string>("titleType")
                        .HasColumnType("text")
                        .HasColumnName("title_type");

                    b.HasKey("tconst");

                    b.ToTable("title_basics", "movie_app");
                });

            modelBuilder.Entity("MovieAppPortfolio.DataServiceLayer.entities.TitleRating", b =>
                {
                    b.Property<string>("tconst")
                        .HasColumnType("text")
                        .HasColumnName("tconst");

                    b.Property<decimal?>("averageRating")
                        .HasColumnType("numeric")
                        .HasColumnName("average_rating");

                    b.Property<int?>("numVotes")
                        .HasColumnType("integer")
                        .HasColumnName("num_votes");

                    b.HasKey("tconst");

                    b.ToTable("title_ratings", "movie_app");
                });

            modelBuilder.Entity("MovieAppPortfolio.DataServiceLayer.entities.UserNote", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("note_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NoteId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note_text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("nconst")
                        .HasColumnType("text")
                        .HasColumnName("nconst");

                    b.Property<string>("tconst")
                        .HasColumnType("text")
                        .HasColumnName("tconst");

                    b.HasKey("NoteId");

                    b.HasIndex("UserId");

                    b.HasIndex("nconst");

                    b.HasIndex("tconst");

                    b.ToTable("user_note", "movie_app");
                });

            modelBuilder.Entity("MovieAppPortfolio.DataServiceLayer.entities.UserRating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rating_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RatingId"));

                    b.Property<DateTime>("RatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rated_at");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("TConst")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tconst");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("RatingId");

                    b.HasIndex("TConst");

                    b.HasIndex("UserId");

                    b.ToTable("user_rating", "movie_app");
                });

            modelBuilder.Entity("MovieAppPortfolio.DataServiceLayer.user.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("app_user", "movie_app");
                });

            modelBuilder.Entity("MovieAppPortfolio.DataServiceLayer.entities.Bookmark", b =>
                {
                    b.HasOne("MovieAppPortfolio.DataServiceLayer.entities.NameBasic", "NameBasic")
                        .WithMany()
                        .HasForeignKey("NConst");

                    b.HasOne("MovieAppPortfolio.DataServiceLayer.entities.TitleBasic", "TitleBasic")
                        .WithMany()
                        .HasForeignKey("TConst");

                    b.HasOne("MovieAppPortfolio.DataServiceLayer.user.User", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NameBasic");

                    b.Navigation("TitleBasic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieAppPortfolio.DataServiceLayer.entities.NameRating", b =>
                {
                    b.HasOne("MovieAppPortfolio.DataServiceLayer.entities.NameBasic", "NameBasic")
                        .WithMany()
                        .HasForeignKey("NameBasicnconst");

                    b.Navigation("NameBasic");
                });

            modelBuilder.Entity("MovieAppPortfolio.DataServiceLayer.entities.SearchHistory", b =>
                {
                    b.HasOne("MovieAppPortfolio.DataServiceLayer.user.User", "User")
                        .WithMany("SearchHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieAppPortfolio.DataServiceLayer.entities.UserNote", b =>
                {
                    b.HasOne("MovieAppPortfolio.DataServiceLayer.user.User", "User")
                        .WithMany("UserNotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieAppPortfolio.DataServiceLayer.entities.NameBasic", "NameBasic")
                        .WithMany()
                        .HasForeignKey("nconst");

                    b.HasOne("MovieAppPortfolio.DataServiceLayer.entities.TitleBasic", "TitleBasic")
                        .WithMany()
                        .HasForeignKey("tconst");

                    b.Navigation("NameBasic");

                    b.Navigation("TitleBasic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieAppPortfolio.DataServiceLayer.entities.UserRating", b =>
                {
                    b.HasOne("MovieAppPortfolio.DataServiceLayer.entities.TitleBasic", "TitleBasic")
                        .WithMany()
                        .HasForeignKey("TConst")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieAppPortfolio.DataServiceLayer.user.User", "User")
                        .WithMany("UserRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TitleBasic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieAppPortfolio.DataServiceLayer.user.User", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("SearchHistories");

                    b.Navigation("UserNotes");

                    b.Navigation("UserRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
